apiVersion: heat.openstack.org/v1beta1
kind: HeatAPI
metadata:
  name: heat-api
spec:
  databaseHostname: openstack
  databaseUser: heat
  passwordSelectors:
    authEncryptionKey: HeatAuthEncryptionKey
    database: HeatDatabasePassword
    service: HeatPassword
  replicas: 1
  resources: {}
  secret: osp-secret
  serviceAccount: heat-heat
  serviceUser: heat
  transportURLSecret: rabbitmq-transport-url-heat-heat-transport
