apiVersion: heat.openstack.org/v1beta1
kind: HeatEngine
metadata:
  name: heat-engine
spec:
  databaseHostname: openstack
  databaseAccount: heat
  passwordSelectors:
    authEncryptionKey: HeatAuthEncryptionKey
    service: HeatPassword
  replicas: 1
  resources: {}
  secret: osp-secret
  serviceAccount: heat-heat
  serviceUser: heat
  transportURLSecret: rabbitmq-transport-url-heat-heat-transport
